---
abstract: 'Convert from and to *.xls, *.csv using Win32::OLE'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-Scsv
no_index:
  directory:
    - t
    - inc
requires:
  Win32::OLE: '0'
  Win32::OLE::Variant: '0'
resources:
  repository: https://github.com/klaus03/Win32-Scsv.git
version: '0.16'
