---
abstract: 'Convert Excel file to CSV using Win32::OLE'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-Scsv
provides:
  Win32::Scsv:
    file: lib/Win32/Scsv.pm
    version: 0.01
requires:
  Win32::OLE: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
